language: go

go:
  - "1.10.x"

install:
  - go get -u github.com/astaxie/beego
  - go get -u github.com/astaxie/beego/context
  - go get -u github.com/go-redis/redis
  - go get -u github.com/google/uuid


notifications:
  email: true