language: go

go:
  - "1.10.x"

before_install:
  - mkdir -p ${GOPATH}/src

install:
  - go get -u github.com/astaxie/beego

script:
  - cd ${GOPATH}/src/github.com/fakegeass/notes

notifications:
  email: false