language: go

go:
  - "1.10.x"

before_install:
  - mkdir -p ${GOPATH}/src

install:
  - go get -u github.com/astaxie/beego

before_script:
  - cd ${GOPATH}/src/github.com/fakegeass/notes 

script:
  - go test -v ./...
  - staticcheck -show-ignored -checks "-ST1017,-U1000,-ST1005,-S1034,-S1012,-SA4006,-SA6005,-SA1019,-SA1024"
  - unconvert $(go list ./... | grep -v /vendor/)
  - ineffassign .
  - find . ! \( -path './vendor' -prune \) -type f -name '*.go' -print0 | xargs -0 gofmt -l -s
  - golint ./...

notifications:
  email: false